# Generated by Django 2.2.5 on 2019-09-15 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('sender', models.CharField(blank=True, default='', max_length=256)),
                ('head', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.CharField(blank=True, default='', max_length=256)),
                ('icon', models.CharField(blank=True, default='', max_length=256)),
                ('sound', models.CharField(blank=True, default='', max_length=256)),
                ('url', models.CharField(blank=True, default='', max_length=256)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_receiver', to='auth.Group')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('head_data', models.CharField(blank=True, default='', max_length=64)),
                ('body_data', models.CharField(blank=True, default='', max_length=256)),
                ('url_data', models.CharField(blank=True, default='', max_length=256)),
                ('head_payload', models.CharField(blank=True, default='', max_length=64)),
                ('body_payload', models.CharField(blank=True, default='', max_length=256)),
                ('url_payload', models.CharField(blank=True, default='', max_length=256)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_content', to='pollen.Content')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created'],
            },
        ),
    ]
