# Generated by Django 2.2.5 on 2019-09-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body_payload',
        ),
        migrations.RemoveField(
            model_name='message',
            name='head_payload',
        ),
        migrations.RemoveField(
            model_name='message',
            name='url_payload',
        ),
    ]
